using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace alch_ingr_getter
{
    public static class Program
    {
        internal static Lazy<Settings> _lazySettings = null!;
        internal static Settings Settings => _lazySettings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            FileInterface IO = new(Settings.filename);

            List<string> data = new();

            Console.WriteLine($"\n\nConfiguration\n\tOut File:\t{Settings.filename}");
            Console.WriteLine("\n\n=== Beginning Process. ===\nGetting a list of all ingredients...\n");

            int count = 0;
            foreach( var ingr in state.LoadOrder.PriorityOrder.Ingredient().WinningOverrides().Where(i => i.EditorID != null))
            {
                data.AddRange(Formatter.FormatIngredient(ingr, state));
                ++count;
            }

            Console.WriteLine("\n\n=== Process Completed. ===\nWriting to file...\n");

            IO.Write(ref data);

            Console.WriteLine($"Successfully wrote {count} ingredients to \"{Settings.filename}\"\n");
        }
    }
}
